# AI Hunters ComfyFlow - cb2c_py/nodes/generate_nodes.py
"""Generate typed Python wrappers for every node exposed by a ComfyUI server.

    python -m cb2c_py.nodes.generate_nodes            # uses COMFYUI_SERVER_ADDRESS
"""
import os
import json
import re
from typing import Dict, List, Any, Optional

from .node_discovery import fetch_node_definitions, COMFYUI_API_URL

DEFAULT_OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "generated")

CLASS_TEMPLATE = '''
# This file is auto-generated by generate_nodes.py
# Do not edit this file directly.

from ..base_node import Node, InputSlots, OutputSlots, Slot, Model, Conditioning, Latent, Image, Vae, Clip
from typing import Dict, Any, List, Union, Literal, Optional, Union

# Define input and output slot classes for {class_name}
class {class_name}Inputs(InputSlots):
{input_slots_annotations}
    def __init__(self, node: "Node"):
{input_slots_assignments}

class {class_name}Outputs(OutputSlots):
{output_slots_annotations}
    def __init__(self, node: "Node"):
{output_slots_assignments}

class {class_name}(Node[{class_name}Inputs, {class_name}Outputs]):
    """
    Original name: {original_name}
    Category: {category}
    {description}

    Inputs:
{inputs_doc}

    Outputs:
{outputs_doc}
    """
    _original_name: str = {original_name_repr}

    def __init__(self, {init_params}):
        super().__init__(**{super_init_params})
        self.inputs = {class_name}Inputs(self)
        self.outputs = {class_name}Outputs(self)
'''

# Inputs that hold model filenames, mapped to their models.json category.
MODEL_INPUT_MAP = {
    "ckpt_name": "checkpoints",
    "vae_name": "vae",
    "clip_name": "text_encoders",
    "clip_name1": "text_encoders",
    "clip_name2": "text_encoders",
    "lora_name": "loras",
    "control_net_name": "controlnet",
    "model_path": "diffusion_models",
    "unet_name": "unet",
}


def sanitize_name(name: str) -> str:
    """Converts a name into a valid Python identifier."""
    sanitized = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if sanitized and sanitized[0].isdigit():
        sanitized = "_" + sanitized
    return sanitized


def _escape_doc(text: Any) -> str:
    """Makes text safe to embed inside a triple-quoted docstring."""
    return str(text).replace("\\", "\\\\").replace('"' * 3, "'" * 3)


def get_python_type(slot_type: Any) -> str:
    """Maps a ComfyUI slot type to a Python type hint."""
    if isinstance(slot_type, list):
        if not slot_type:
            return "str"
        literal_type = f"Literal[{', '.join(repr(v) for v in slot_type)}]"
        return f"Union[{literal_type}, str]"

    type_map = {"INT": "int", "FLOAT": "float", "STRING": "str", "BOOLEAN": "bool"}
    if str(slot_type) in type_map:
        return type_map[str(slot_type)]

    slot_type_map = {
        "MODEL": "Slot[Model]", "CONDITIONING": "Slot[Conditioning]",
        "LATENT": "Slot[Latent]", "IMAGE": "Slot[Image]", "VAE": "Slot[Vae]",
        "CLIP": "Slot[Clip]", "MASK": "Slot[Image]",
    }
    return slot_type_map.get(str(slot_type), "Slot[Any]")


def get_python_type_for_input(slot_type: Any, default_value: Optional[Any]) -> str:
    """Python type for an input; a Union when the default's type differs."""
    if isinstance(slot_type, list) and not slot_type:
        return "str"
    primary_py_type = get_python_type(slot_type)
    if str(slot_type) == "COMBO":
        return "str"
    if default_value is None:
        return primary_py_type

    default_py_type = ""
    if isinstance(default_value, str):
        default_py_type = "str"
    elif isinstance(default_value, bool):
        default_py_type = "bool"
    elif isinstance(default_value, float):
        default_py_type = "float"
    elif isinstance(default_value, int):
        default_py_type = "int"

    if default_py_type and primary_py_type != default_py_type and "Slot" not in primary_py_type:
        return f"Union[{primary_py_type}, {default_py_type}]"
    return primary_py_type


def get_valid_default_value(default_value: Any, slot_type: Any) -> str:
    """repr of the default value, forced to str for COMBOs."""
    if isinstance(slot_type, list) or str(slot_type) == "COMBO":
        return repr(str(default_value))
    return repr(default_value)


def _load_available_models(models_json_path: Optional[str]) -> Dict[str, List[str]]:
    """Returns ``{category: [model names]}`` from a v2 or legacy models.json."""
    if not models_json_path or not os.path.exists(models_json_path):
        return {}
    with open(models_json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    result: Dict[str, List[str]] = {}
    if isinstance(data, dict) and isinstance(data.get("models"), list):
        for m in data["models"]:
            if m.get("name"):
                result.setdefault(m.get("category", "checkpoints"), []).append(m["name"])
        return result
    for category, models in data.items():
        if isinstance(models, dict):
            result[category] = list(models.keys())
    return result


def _input_type(config: Any):
    """Returns ``(slot_type, opts)`` for an /object_info input config."""
    if not isinstance(config, (list, tuple)) or not config:
        return None, {}
    slot_type = config[0]
    opts = config[1] if len(config) > 1 and isinstance(config[1], dict) else {}
    if slot_type == "COMBO" and isinstance(opts.get("options"), list):
        slot_type = opts["options"]
    return slot_type, opts


def generate_node_files(
    api_url: str = COMFYUI_API_URL,
    node_definitions: Optional[Dict[str, Any]] = None,
    models_json_path: Optional[str] = None,
    output_dir: Optional[str] = None,
) -> int:
    """Generates one module per node plus the package ``__init__``.

    Uses ``node_definitions`` when given, otherwise fetches ``/object_info``
    from ``api_url``. Returns the number of generated classes.
    """
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    print("Starting node generation process...")
    if node_definitions is None:
        node_definitions = fetch_node_definitions(api_url)
    if not node_definitions:
        print("Could not fetch node definitions. Aborting.")
        return 0

    if models_json_path is None:
        models_json_path = os.getenv("MODELS_DB_PATH", "")
    available_models = _load_available_models(models_json_path)

    os.makedirs(out_dir, exist_ok=True)
    generated_classes: Dict[str, str] = {}

    for original_name, details in node_definitions.items():
        class_name = sanitize_name(original_name)
        if not class_name or class_name in generated_classes:
            print(f"Warning: Sanitized name collision for '{original_name}'. Skipping.")
            continue

        inputs_data = dict((details.get("input") or {}).get("required") or {})
        optional_inputs = (details.get("input") or {}).get("optional") or {}
        is_optional = {k: False for k in inputs_data.keys()}
        if optional_inputs:
            inputs_data.update(optional_inputs)
            is_optional.update({k: True for k in optional_inputs.keys()})

        processed_inputs = []
        for name, config in inputs_data.items():
            slot_type, param_opts = _input_type(config)
            if slot_type is None:
                continue
            s_name = sanitize_name(name)
            if s_name in MODEL_INPUT_MAP and isinstance(slot_type, list):
                model_category = MODEL_INPUT_MAP[s_name]
                if model_category in available_models:
                    slot_type = sorted(set(slot_type + available_models[model_category]))
            processed_inputs.append({
                "name": name,
                "s_name": s_name,
                "slot_type": slot_type,
                "param_opts": param_opts,
                "is_optional": is_optional.get(name, False),
            })

        input_slots_annotations, input_slots_assignments, inputs_doc_list = [], [], []
        for p_input in processed_inputs:
            s_name, slot_type, param_opts = p_input["s_name"], p_input["slot_type"], p_input["param_opts"]
            default_val = param_opts.get("default")
            tooltip = param_opts.get("tooltip")
            py_type = get_python_type_for_input(slot_type, default_val)
            slot_py_type = py_type if "Slot" in py_type else f"Slot[{py_type}]"
            input_slots_annotations.append(f"    {s_name}: {slot_py_type}")
            input_slots_assignments.append(
                f'        self.{s_name} = {slot_py_type}(node, "{s_name}", {repr(slot_type)})'
            )
            doc_type = get_python_type(slot_type).replace("Slot[", "").replace("]", "")
            doc_line = f"        - {s_name} ({doc_type})"
            if "default" in param_opts:
                doc_line += f" (default: {get_valid_default_value(default_val, slot_type)})"
            if tooltip:
                doc_line += f"\n          {tooltip}"
            inputs_doc_list.append(doc_line)

        if not input_slots_assignments:
            input_slots_assignments.append("        pass")
        if not inputs_doc_list:
            inputs_doc_list.append("        No inputs.")

        output_slots_annotations, output_slots_assignments, outputs_doc_list = [], [], []
        output_tooltips = details.get("output_tooltips") or []
        output_names = details.get("output_name") or details.get("output") or []
        used_props = set()
        for i, (name, slot_type) in enumerate(zip(output_names, details.get("output") or [])):
            prop_name = sanitize_name(str(name).lower()) or f"output_{i}"
            if prop_name in used_props:
                prop_name = f"{prop_name}_{i}"
            used_props.add(prop_name)
            py_type = get_python_type(slot_type)
            slot_py_type = py_type if "Slot" in py_type else f"Slot[{py_type}]"
            output_slots_annotations.append(f"    {prop_name}: {slot_py_type}")
            output_slots_assignments.append(
                f'        self.{prop_name} = {slot_py_type}(node, {repr(str(name))}, {repr(slot_type)}, index={i})'
            )
            doc_type = py_type.replace("Slot[", "").replace("]", "")
            doc_line = f"        - {prop_name} ({doc_type})"
            if i < len(output_tooltips) and output_tooltips[i]:
                doc_line += f"\n          {output_tooltips[i]}"
            outputs_doc_list.append(doc_line)

        if not output_slots_assignments:
            output_slots_assignments.append("        pass")
        if not outputs_doc_list:
            outputs_doc_list.append("        No outputs.")

        params_with_defaults, params_without_defaults = [], []
        for p_input in processed_inputs:
            s_name, slot_type, param_opts = p_input["s_name"], p_input["slot_type"], p_input["param_opts"]
            py_type = get_python_type_for_input(slot_type, param_opts.get("default"))
            init_py_type = py_type.replace("Slot[", "").replace("]", "") if "Slot" in py_type else py_type
            if "Slot" in py_type:
                init_py_type = f"Union[{py_type}, {init_py_type}]"
            if "default" in param_opts:
                default_value_str = get_valid_default_value(param_opts.get("default"), slot_type)
                params_with_defaults.append(f"{s_name}: {init_py_type} = {default_value_str}")
            elif p_input.get("is_optional"):
                params_with_defaults.append(f"{s_name}: Optional[{init_py_type}] = None")
            else:
                params_without_defaults.append(f"{s_name}: {init_py_type}")

        init_params_list = params_without_defaults + params_with_defaults
        super_init_params_list = [f'{p_input["name"]!r}: {p_input["s_name"]}' for p_input in processed_inputs]

        file_content = CLASS_TEMPLATE.format(
            class_name=class_name,
            original_name=_escape_doc(original_name),
            original_name_repr=repr(original_name),
            category=_escape_doc(details.get("category", "Unknown")),
            description=_escape_doc(details.get("description") or "No description available."),
            inputs_doc=_escape_doc("\n".join(inputs_doc_list)),
            outputs_doc=_escape_doc("\n".join(outputs_doc_list)),
            input_slots_annotations="\n".join(input_slots_annotations),
            input_slots_assignments="\n".join(input_slots_assignments),
            output_slots_annotations="\n".join(output_slots_annotations),
            output_slots_assignments="\n".join(output_slots_assignments),
            init_params=", ".join(init_params_list),
            super_init_params=f"{{{', '.join(super_init_params_list)}}}",
        ).replace("def __init__(self, ):", "def __init__(self):")

        module_name = class_name.lower()
        with open(os.path.join(out_dir, f"{module_name}.py"), "w", encoding="utf-8") as f:
            f.write(file_content)
        generated_classes[class_name] = module_name

    print(f"\nSuccessfully generated {len(generated_classes)} node files.")

    sorted_class_names = sorted(generated_classes.keys())
    import_lines = [f"from .{generated_classes[name]} import {name}" for name in sorted_class_names]

    aliases: Dict[str, str] = {}
    for original_name, details in node_definitions.items():
        class_name = sanitize_name(original_name)
        if class_name not in generated_classes:
            continue
        for name, config in ((details.get("input") or {}).get("required") or {}).items():
            slot_type, _ = _input_type(config)
            if isinstance(slot_type, list) and slot_type:
                alias = f"{class_name}{sanitize_name(name).capitalize()}"
                if alias not in generated_classes:
                    aliases[alias] = f"Literal[{', '.join(repr(v) for v in slot_type)}]"

    with open(os.path.join(out_dir, "__init__.py"), "w", encoding="utf-8") as f:
        f.write("# This file is auto-generated by generate_nodes.py. Do not edit.\n")
        f.write("from typing import Literal\n\n")
        f.write("\n".join(import_lines))
        f.write("\n\n")
        f.write("\n".join(f"{k} = {v}" for k, v in aliases.items()))
        all_list = sorted_class_names + list(aliases.keys())
        f.write(f"\n\n__all__ = {json.dumps(all_list, indent=4)}\n")
    print("Successfully created __init__.py.")
    print("\nNode generation complete.")
    return len(generated_classes)


if __name__ == "__main__":
    generate_node_files()
